syntax = "proto3";

package proto.event.authn;
import "google/protobuf/empty.proto";
import "proto/event/authority.proto";
import "proto/ident.proto";
import "proto/event/timestamp.proto";

message ProtoAuthnEvent {
  message ProtoUserCreated {
    proto.ident.ProtoIdent user_id = 1;
    string email = 2;
    bytes webauthn_uuid = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoUserDeleted {
    proto.ident.ProtoIdent user_id = 1;
    proto.event.authority.ProtoAuthority authority = 2;
    proto.event.timestamp.ProtoTimestamp timestamp = 3;
  }

  message ProtoPasskeyCreated {
    proto.ident.ProtoIdent passkey_id = 1;
    proto.ident.ProtoIdent user_id = 2;
    bytes passkey = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoPasskeyDeleted {
    proto.ident.ProtoIdent passkey_id = 1;
    proto.event.authority.ProtoAuthority authority = 2;
    proto.event.timestamp.ProtoTimestamp timestamp = 3;
  }

  oneof authn_event_type {
    ProtoUserCreated user_created = 1;
    ProtoUserDeleted user_deleted = 2;
    ProtoPasskeyCreated passkey_created = 3;
    ProtoPasskeyDeleted passkey_deleted = 4;
  }
}