syntax = "proto3";

package proto.event.authz;

import "google/protobuf/empty.proto";
import "proto/event/authority.proto";
import "proto/ident.proto";
import "proto/event/timestamp.proto";

message ProtoAuthzEvent {
  message ProtoRoleCreated {
    proto.ident.ProtoIdent role_id = 1;
    string name = 2;
    proto.event.authority.ProtoAuthority authority = 3;
    proto.event.timestamp.ProtoTimestamp timestamp = 4;
  }

  message ProtoRoleActorAdded {
    proto.ident.ProtoIdent role_id = 1;
    proto.event.authority.ProtoActor actor = 2;
    proto.event.authority.ProtoAuthority authority = 3;
    proto.event.timestamp.ProtoTimestamp timestamp = 4;
  }

  message ProtoRoleActorRemoved {
    proto.ident.ProtoIdent role_id = 1;
    proto.event.authority.ProtoActor actor = 2;
    proto.event.authority.ProtoAuthority authority = 3;
    proto.event.timestamp.ProtoTimestamp timestamp = 4;
  }

  message ProtoGrantCreated {
    proto.ident.ProtoIdent grant_id = 1;
    proto.ident.ProtoIdent role_id = 2;
    proto.event.authority.ProtoAuthority authority = 3;
    proto.event.timestamp.ProtoTimestamp timestamp = 4;
  }

  message ProtoGrantRevoked {
    proto.ident.ProtoIdent grant_id = 1;
    proto.event.authority.ProtoAuthority authority = 2;
    proto.event.timestamp.ProtoTimestamp timestamp = 3;
  }

  oneof authz_event_type {
    ProtoRoleCreated role_created = 1;
    ProtoRoleActorAdded role_actor_added = 2;
    ProtoRoleActorRemoved role_actor_removed = 3;
    ProtoGrantCreated grant_created = 4;
    ProtoGrantRevoked grant_revoked = 5;
  }
}