syntax = "proto3";

package proto.event.journal;

import "google/protobuf/empty.proto";
import "proto/event/authority.proto";
import "proto/ident.proto";
import "proto/event/timestamp.proto";
import "proto/balance_update.proto";


message ProtoJournalDomainEvent {
  message ProtoJournalCreated {
    proto.ident.ProtoIdent journal_id = 1;
    proto.ident.ProtoIdent owner_id = 2;
    string name = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoJournalDeleted {
    proto.ident.ProtoIdent journal_id = 1;
    proto.event.authority.ProtoAuthority authority = 2;
    proto.event.timestamp.ProtoTimestamp timestamp = 3;
  }

  message ProtoMemberAdded {
    proto.ident.ProtoIdent journal_id = 1;
    proto.ident.ProtoIdent user_id = 2;
    int32 permissions = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoMemberPermissionsUpdated {
    proto.ident.ProtoIdent journal_id = 1;
    proto.ident.ProtoIdent user_id = 2;
    int32 permissions = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoMemberRemoved {
    proto.ident.ProtoIdent journal_id = 1;
    proto.ident.ProtoIdent user_id = 2;
    proto.event.authority.ProtoAuthority authority = 3;
    proto.event.timestamp.ProtoTimestamp timestamp = 4;
  }

  message ProtoAccountCreated {
    proto.ident.ProtoIdent account_id = 1;
    proto.ident.ProtoIdent journal_id = 2;
    string name = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoAccountRenamed {
    proto.ident.ProtoIdent account_id = 1;
    string new_name = 2;
    proto.event.authority.ProtoAuthority authority = 3;
    proto.event.timestamp.ProtoTimestamp timestamp = 4;
  }

  message ProtoAccountDeleted {
    proto.ident.ProtoIdent account_id = 1;
    proto.event.authority.ProtoAuthority authority = 2;
    proto.event.timestamp.ProtoTimestamp timestamp = 3;
  }

  message ProtoTransactionCreated {
    proto.ident.ProtoIdent transaction_id = 1;
    proto.ident.ProtoIdent journal_id = 2;
    proto.balance_update.RepeatedBalanceUpdates entries = 3;
    proto.event.authority.ProtoAuthority authority = 4;
    proto.event.timestamp.ProtoTimestamp timestamp = 5;
  }

  message ProtoTransactionDeleted {
    proto.ident.ProtoIdent transaction_id = 1;
    proto.event.authority.ProtoAuthority authority = 2;
    proto.event.timestamp.ProtoTimestamp timestamp = 3;
  }

  oneof journal_domain_event_type {
    ProtoJournalCreated journal_created = 1;
    ProtoJournalDeleted journal_deleted = 2;
    ProtoMemberAdded member_added = 3;
    ProtoMemberPermissionsUpdated member_permissions_updated = 4;
    ProtoMemberRemoved member_removed = 5;
    ProtoAccountCreated account_created = 6;
    ProtoAccountRenamed account_renamed = 7;
    ProtoAccountDeleted account_deleted = 8;
    ProtoTransactionCreated transaction_created = 9;
    ProtoTransactionDeleted transaction_deleted = 10;
  }
}