#!/bin/sh
set -e
cargo fmt --all > /dev/null 2>&1

cargo sqlx prepare -- --all-targets

# Check if anything changed in the .sqlx directory
if [ -d ".sqlx" ]; then
    git add .sqlx
fi

cargo clippy -- -D warnings

if [ $? -ne 0 ]; then
    echo "Clippy failed, commit aborted"
    exit 1
fi

git diff --quiet || git add -u
exit 0
