syntax = "proto3";

package proto.error;

import "google/protobuf/empty.proto";
import "ident.proto";
import "balance_update.proto";

message ProtoIdentError {
  oneof ident_error_type {
    string parse = 1;
    string invalid_id = 2;
  }
}

message ProtoNameError {
  oneof name_error_type {
    string too_short = 1;
    string too_long = 2;
  }
}

message ProtoJournalError {
  message ProtoTransactionValidationError {

    oneof transaction_validation_error_type {
      string invalid_entry_type = 1;
      google.protobuf.Empty no_transaction_entries = 2;
      google.protobuf.Empty missing_entry_amount = 3;
      google.protobuf.Empty missing_entry_type = 4;
      string parse_decimal = 5;
      string partial_cent_value = 6;
      string out_of_range = 7;
      string negative_entry_amount = 8;
      balance_update.RepeatedBalanceUpdates imbalanced_transaction = 9;
    }
  }

  oneof journal_error_type {
    ident.ProtoIdent id_collision = 1;
    ident.ProtoIdent account_id_collision = 2;
    ident.ProtoIdent transaction_id_collision = 3;
    ident.ProtoIdent invalid_journal = 4;
    ident.ProtoIdent invalid_account = 5;
    ident.ProtoIdent invalid_transaction = 6;
    int32 permissions = 7;
    ident.ProtoIdent user_already_has_access = 8;
    ident.ProtoIdent user_doesnt_have_access = 9;
    ProtoIdentError ident_creation = 10;
    string event_decode = 11;
    string sqlx = 12;
    int32 permission_decode = 13;
    ProtoTransactionValidationError transaction_validation = 14;
    ProtoDecodeError proto_decode = 15;
    ident.ProtoIdent file_id_collision = 16;
    google.protobuf.Empty invalid_S3_credentials = 17;
    string s3 = 18;
    ident.ProtoIdent invalid_file = 19;
  }
}

message ProtoUserError {

  oneof user_error_type {
    string email_conflict = 1;
    string email_doesnt_exist = 2;
    ident.ProtoIdent id_collision = 3;
    ident.ProtoIdent user_doesnt_exist = 4;
    string passkey_decode = 5;
    google.protobuf.Empty session_not_found = 6;
    string sqlx = 7;
    string seed_failure = 8;
    google.protobuf.Empty invalid_input = 9;
    string serde_json = 10;
    string session = 11;
    google.protobuf.Empty authentication_failed = 12;
    google.protobuf.Empty missing_resend_api_key = 13;
    string resend = 14;
    google.protobuf.Empty invalid_verification_code = 15;
  }
}

message ProtoPasskeyError {
  oneof passkey_error_type {
    google.protobuf.Empty session_expired = 1;
    google.protobuf.Empty invalid_input = 2;
    string session_error = 3;
    ident.ProtoIdent id_conflict = 4;
    ident.ProtoIdent passkey_doesnt_exist = 5;
    ident.ProtoIdent user_doesnt_exist = 6;
    string json = 7;
    string sqlx = 8;
  }
}

message ProtoDecodeError {
  oneof proto_error_type {
    google.protobuf.Empty deserialize = 1;
    google.protobuf.Empty field_required = 2;
    int32 permission_decode = 3;
    string parse_email = 4;
    ProtoIdentError ident = 5;
    string uuid = 6;
    ProtoNameError name = 7;
  }
}

message ProtoMonkestoError {
  oneof monkesto_error_type {
    ProtoDecodeError error_decode = 1;
    ProtoNameError name_creation = 2;
    ProtoIdentError ident_creation = 3;
    string email_creation = 4;
    ProtoJournalError journal = 5;
    ProtoUserError user = 6;
    string disintegrate_event = 7;
    string disintegrate_state = 8;
    ProtoPasskeyError passkey = 9;
  }
}



